<--DROP TABLE IF EXISTS ARTIST;
--CREATE TABLE ARTIST(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), CONTACT_EMAIL VARCHAR(255));
--INSERT INTO ARTIST VALUES('Juuk', 'juuk@juuk.con');
--INSERT INTO ARTIST VALUES('Juuk', 'juuk@juuk.con');-->